// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: c4echain/cfetokenization/params.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	_ "google.golang.org/protobuf/types/known/durationpb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the module.
type Params struct {
	ActionTimeWindow        time.Duration                          `protobuf:"bytes,1,opt,name=action_time_window,json=actionTimeWindow,proto3,stdduration" json:"action_time_window"`
	MarketplaceFee          github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,2,opt,name=marketplace_fee,json=marketplaceFee,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"marketplace_fee"`
	AuthorityFee            github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,3,opt,name=authority_fee,json=authorityFee,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"authority_fee"`
	MarketplaceOwnerAddress string                                 `protobuf:"bytes,4,opt,name=marketplace_owner_address,json=marketplaceOwnerAddress,proto3" json:"marketplace_owner_address,omitempty"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_72073232f0e044ca, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetActionTimeWindow() time.Duration {
	if m != nil {
		return m.ActionTimeWindow
	}
	return 0
}

func (m *Params) GetMarketplaceOwnerAddress() string {
	if m != nil {
		return m.MarketplaceOwnerAddress
	}
	return ""
}

func init() {
	proto.RegisterType((*Params)(nil), "chain4energy.c4echain.cfetokenization.Params")
}

func init() {
	proto.RegisterFile("c4echain/cfetokenization/params.proto", fileDescriptor_72073232f0e044ca)
}

var fileDescriptor_72073232f0e044ca = []byte{
	// 364 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0x4f, 0x6b, 0xf2, 0x40,
	0x10, 0x87, 0x13, 0x5f, 0x91, 0xb7, 0xe9, 0x5f, 0x42, 0xa1, 0xea, 0x21, 0x91, 0x82, 0xc5, 0x8b,
	0xbb, 0xd0, 0x7a, 0xa9, 0xb7, 0x8a, 0xf4, 0xda, 0x56, 0x0b, 0x42, 0x2f, 0x61, 0xdd, 0x8c, 0x71,
	0xd1, 0x64, 0xc3, 0x66, 0x83, 0xb5, 0x9f, 0xa2, 0x47, 0x8f, 0xfd, 0x38, 0x42, 0x2f, 0x1e, 0x4b,
	0x0f, 0xb6, 0xe8, 0x17, 0x29, 0xd9, 0x68, 0x09, 0xed, 0xad, 0xa7, 0x64, 0xf9, 0xcd, 0xf3, 0xcc,
	0xb0, 0x3b, 0x46, 0x95, 0x36, 0x80, 0x0e, 0x09, 0x0b, 0x30, 0x1d, 0x80, 0xe4, 0x23, 0x08, 0xd8,
	0x13, 0x91, 0x8c, 0x07, 0x38, 0x24, 0x82, 0xf8, 0x11, 0x0a, 0x05, 0x97, 0xdc, 0xac, 0xaa, 0x9a,
	0x06, 0x04, 0x20, 0xbc, 0x29, 0xda, 0x32, 0xe8, 0x07, 0x53, 0x3e, 0xf6, 0xb8, 0xc7, 0x15, 0x81,
	0x93, 0xbf, 0x14, 0x2e, 0x5b, 0x1e, 0xe7, 0xde, 0x18, 0xb0, 0x3a, 0xf5, 0xe3, 0x01, 0x76, 0x63,
	0xa1, 0xea, 0xd3, 0xfc, 0xf4, 0x35, 0x67, 0x14, 0x6e, 0x55, 0x37, 0xf3, 0xce, 0x30, 0x09, 0x4d,
	0x22, 0x47, 0x32, 0x1f, 0x9c, 0x09, 0x0b, 0x5c, 0x3e, 0x29, 0xea, 0x15, 0xbd, 0xb6, 0x7b, 0x5e,
	0x42, 0xa9, 0x07, 0x6d, 0x3d, 0xa8, 0xbd, 0xf1, 0xb4, 0xfe, 0xcf, 0x97, 0xb6, 0x36, 0xfb, 0xb0,
	0xf5, 0xce, 0x51, 0x8a, 0xdf, 0x33, 0x1f, 0x7a, 0x0a, 0x36, 0x7b, 0xc6, 0xa1, 0x4f, 0xc4, 0x08,
	0x64, 0x38, 0x26, 0x14, 0x9c, 0x01, 0x40, 0x31, 0x57, 0xd1, 0x6b, 0x3b, 0x2d, 0x94, 0x40, 0xef,
	0x4b, 0xfb, 0xcc, 0x63, 0x72, 0x18, 0xf7, 0x11, 0xe5, 0x3e, 0xa6, 0x3c, 0xf2, 0x79, 0xb4, 0xf9,
	0xd4, 0x23, 0x77, 0x84, 0xe5, 0x34, 0x84, 0x08, 0xb5, 0x81, 0x76, 0x0e, 0x32, 0x9a, 0x6b, 0x00,
	0xb3, 0x6b, 0xec, 0x93, 0x58, 0x0e, 0xb9, 0x60, 0x72, 0xaa, 0xb4, 0xff, 0xfe, 0xa4, 0xdd, 0xfb,
	0x96, 0x24, 0xd2, 0xa6, 0x51, 0xca, 0x4e, 0xcb, 0x27, 0x01, 0x08, 0x87, 0xb8, 0xae, 0x80, 0x28,
	0x2a, 0xe6, 0x93, 0x06, 0x9d, 0x93, 0x4c, 0xc1, 0x4d, 0x92, 0x5f, 0xa5, 0x71, 0x33, 0x3f, 0x7b,
	0xb1, 0xb5, 0x56, 0x77, 0xbe, 0xb2, 0xf4, 0xc5, 0xca, 0xd2, 0x3f, 0x57, 0x96, 0xfe, 0xbc, 0xb6,
	0xb4, 0xc5, 0xda, 0xd2, 0xde, 0xd6, 0x96, 0xf6, 0x70, 0x99, 0x9d, 0x28, 0xf3, 0x9e, 0x98, 0x36,
	0xa0, 0x9e, 0x2e, 0xc1, 0xe3, 0xaf, 0x35, 0x50, 0x83, 0xf6, 0x0b, 0xea, 0xce, 0x2f, 0xbe, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x4b, 0x39, 0x90, 0xa3, 0x2f, 0x02, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MarketplaceOwnerAddress) > 0 {
		i -= len(m.MarketplaceOwnerAddress)
		copy(dAtA[i:], m.MarketplaceOwnerAddress)
		i = encodeVarintParams(dAtA, i, uint64(len(m.MarketplaceOwnerAddress)))
		i--
		dAtA[i] = 0x22
	}
	{
		size := m.AuthorityFee.Size()
		i -= size
		if _, err := m.AuthorityFee.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.MarketplaceFee.Size()
		i -= size
		if _, err := m.MarketplaceFee.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	n1, err1 := github_com_gogo_protobuf_types.StdDurationMarshalTo(m.ActionTimeWindow, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdDuration(m.ActionTimeWindow):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintParams(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = github_com_gogo_protobuf_types.SizeOfStdDuration(m.ActionTimeWindow)
	n += 1 + l + sovParams(uint64(l))
	l = m.MarketplaceFee.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.AuthorityFee.Size()
	n += 1 + l + sovParams(uint64(l))
	l = len(m.MarketplaceOwnerAddress)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActionTimeWindow", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdDurationUnmarshal(&m.ActionTimeWindow, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MarketplaceFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MarketplaceFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuthorityFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AuthorityFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MarketplaceOwnerAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MarketplaceOwnerAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
