// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: c4e-chain/cfevesting/genesis.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the cfevesting module's genesis state.
type GenesisState struct {
	Params                   Params                 `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	VestingTypes             []GenesisVestingType   `protobuf:"bytes,2,rep,name=vesting_types,json=vestingTypes,proto3" json:"vesting_types" yaml:"vesting_types"`
	AccountVestingPools      []*AccountVestingPools `protobuf:"bytes,3,rep,name=account_vesting_pools,json=accountVestingPools,proto3" json:"account_vesting_pools,omitempty" yaml:"account_vesting_pools"`
	VestingAccountTraces     []VestingAccountTrace  `protobuf:"bytes,4,rep,name=vesting_account_traces,json=vestingAccountTraces,proto3" json:"vesting_account_traces"`
	VestingAccountTraceCount uint64                 `protobuf:"varint,5,opt,name=vesting_account_trace_count,json=vestingAccountTraceCount,proto3" json:"vesting_account_trace_count,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_3125dced8e1de359, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetVestingTypes() []GenesisVestingType {
	if m != nil {
		return m.VestingTypes
	}
	return nil
}

func (m *GenesisState) GetAccountVestingPools() []*AccountVestingPools {
	if m != nil {
		return m.AccountVestingPools
	}
	return nil
}

func (m *GenesisState) GetVestingAccountTraces() []VestingAccountTrace {
	if m != nil {
		return m.VestingAccountTraces
	}
	return nil
}

func (m *GenesisState) GetVestingAccountTraceCount() uint64 {
	if m != nil {
		return m.VestingAccountTraceCount
	}
	return 0
}

type GenesisVestingType struct {
	// vesting type name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// period of locked coins from vesting start
	LockupPeriod     int64  `protobuf:"varint,2,opt,name=lockup_period,json=lockupPeriod,proto3" json:"lockup_period,omitempty"`
	LockupPeriodUnit string `protobuf:"bytes,3,opt,name=lockup_period_unit,json=lockupPeriodUnit,proto3" json:"lockup_period_unit,omitempty"`
	// period of veesting coins from lockup period end
	VestingPeriod     int64                                  `protobuf:"varint,4,opt,name=vesting_period,json=vestingPeriod,proto3" json:"vesting_period,omitempty"`
	VestingPeriodUnit string                                 `protobuf:"bytes,5,opt,name=vesting_period_unit,json=vestingPeriodUnit,proto3" json:"vesting_period_unit,omitempty"`
	Free              github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,6,opt,name=free,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"free"`
}

func (m *GenesisVestingType) Reset()         { *m = GenesisVestingType{} }
func (m *GenesisVestingType) String() string { return proto.CompactTextString(m) }
func (*GenesisVestingType) ProtoMessage()    {}
func (*GenesisVestingType) Descriptor() ([]byte, []int) {
	return fileDescriptor_3125dced8e1de359, []int{1}
}
func (m *GenesisVestingType) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisVestingType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisVestingType.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisVestingType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisVestingType.Merge(m, src)
}
func (m *GenesisVestingType) XXX_Size() int {
	return m.Size()
}
func (m *GenesisVestingType) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisVestingType.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisVestingType proto.InternalMessageInfo

func (m *GenesisVestingType) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GenesisVestingType) GetLockupPeriod() int64 {
	if m != nil {
		return m.LockupPeriod
	}
	return 0
}

func (m *GenesisVestingType) GetLockupPeriodUnit() string {
	if m != nil {
		return m.LockupPeriodUnit
	}
	return ""
}

func (m *GenesisVestingType) GetVestingPeriod() int64 {
	if m != nil {
		return m.VestingPeriod
	}
	return 0
}

func (m *GenesisVestingType) GetVestingPeriodUnit() string {
	if m != nil {
		return m.VestingPeriodUnit
	}
	return ""
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "chain4energy.c4echain.cfevesting.GenesisState")
	proto.RegisterType((*GenesisVestingType)(nil), "chain4energy.c4echain.cfevesting.GenesisVestingType")
}

func init() {
	proto.RegisterFile("c4e-chain/cfevesting/genesis.proto", fileDescriptor_3125dced8e1de359)
}

var fileDescriptor_3125dced8e1de359 = []byte{
	// 516 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0x41, 0x6f, 0xd3, 0x30,
	0x14, 0xc7, 0x9b, 0x36, 0xab, 0x84, 0xd7, 0x21, 0xf0, 0x0a, 0x8a, 0xca, 0x94, 0x86, 0x20, 0x50,
	0x85, 0x98, 0x23, 0x8d, 0x70, 0x41, 0xe2, 0x40, 0x40, 0x70, 0x43, 0x55, 0x18, 0x1c, 0xb8, 0x44,
	0x9e, 0xe7, 0x65, 0xd1, 0x9a, 0x38, 0xc4, 0x6e, 0xa1, 0x9f, 0x81, 0x03, 0x9c, 0xf8, 0x4c, 0x3b,
	0xee, 0x88, 0x38, 0x54, 0xa8, 0xfd, 0x06, 0xfb, 0x04, 0x28, 0xb6, 0xcb, 0x52, 0x1a, 0xa9, 0x3b,
	0xe5, 0x39, 0xfe, 0xff, 0x7f, 0xef, 0xf9, 0xd9, 0x0f, 0xb8, 0xc4, 0xa7, 0xfb, 0xe4, 0x14, 0x27,
	0x99, 0x47, 0x4e, 0xe8, 0x84, 0x72, 0x91, 0x64, 0xb1, 0x17, 0xd3, 0x8c, 0xf2, 0x84, 0xa3, 0xbc,
	0x60, 0x82, 0x41, 0x47, 0xee, 0xfb, 0x34, 0xa3, 0x45, 0x3c, 0x45, 0xc4, 0xa7, 0x72, 0x8d, 0xae,
	0xf4, 0xbd, 0x6e, 0xcc, 0x62, 0x26, 0xc5, 0x5e, 0x19, 0x29, 0x5f, 0xef, 0x7e, 0x2d, 0x3b, 0xc7,
	0x05, 0x4e, 0x35, 0xba, 0xe7, 0xd5, 0x4a, 0x30, 0x21, 0x6c, 0x9c, 0x89, 0x48, 0xaf, 0xa3, 0x9c,
	0xb1, 0x91, 0x36, 0x3c, 0xae, 0x35, 0x2c, 0x85, 0xda, 0xa8, 0xb4, 0xee, 0x77, 0x13, 0x74, 0xde,
	0xaa, 0x93, 0xbc, 0x17, 0x58, 0x50, 0xf8, 0x06, 0xb4, 0x55, 0x76, 0xcb, 0x70, 0x8c, 0xc1, 0xf6,
	0xc1, 0x00, 0x6d, 0x3a, 0x19, 0x1a, 0x4a, 0x7d, 0x60, 0x9e, 0xcf, 0xfa, 0x8d, 0x50, 0xbb, 0xe1,
	0x17, 0xb0, 0xb3, 0xcc, 0x28, 0xa6, 0x39, 0xe5, 0x56, 0xd3, 0x69, 0x0d, 0xb6, 0x0f, 0xfc, 0xcd,
	0x38, 0x5d, 0xce, 0x47, 0xb5, 0x3c, 0x9c, 0xe6, 0x34, 0xd8, 0x2b, 0xd1, 0x97, 0xb3, 0x7e, 0x77,
	0x8a, 0xd3, 0xd1, 0x73, 0x77, 0x05, 0xec, 0x86, 0x9d, 0xc9, 0x95, 0x94, 0xc3, 0x6f, 0x06, 0xb8,
	0x53, 0xd7, 0x1c, 0x6e, 0xb5, 0x64, 0x05, 0xcf, 0x36, 0x57, 0xf0, 0x52, 0xd9, 0x75, 0x05, 0xc3,
	0xd2, 0x1c, 0x38, 0x97, 0xb3, 0xfe, 0x9e, 0x4a, 0x5f, 0x4b, 0x77, 0xc3, 0x5d, 0xbc, 0x6e, 0x83,
	0x9f, 0xc1, 0xdd, 0xff, 0x1a, 0x1f, 0x89, 0x02, 0x13, 0xca, 0x2d, 0xf3, 0xba, 0xd5, 0x68, 0x9e,
	0x2e, 0xea, 0xb0, 0x74, 0xeb, 0x5e, 0x77, 0x27, 0xeb, 0x5b, 0x1c, 0xbe, 0x00, 0xf7, 0x6a, 0x53,
	0x46, 0x32, 0xb6, 0xb6, 0x1c, 0x63, 0x60, 0x86, 0x56, 0x8d, 0xf5, 0x55, 0x19, 0xb9, 0x3f, 0x9b,
	0x00, 0xae, 0x5f, 0x01, 0x84, 0xc0, 0xcc, 0x70, 0x4a, 0xe5, 0xab, 0xb8, 0x11, 0xca, 0x18, 0x3e,
	0x00, 0x3b, 0x23, 0x46, 0xce, 0xc6, 0x79, 0x94, 0xd3, 0x22, 0x61, 0xc7, 0x56, 0xd3, 0x31, 0x06,
	0xad, 0xb0, 0xa3, 0x7e, 0x0e, 0xe5, 0x3f, 0xf8, 0x04, 0xc0, 0x15, 0x51, 0x34, 0xce, 0x12, 0x61,
	0xb5, 0x24, 0xe6, 0x56, 0x55, 0xf9, 0x21, 0x4b, 0x04, 0x7c, 0x08, 0x6e, 0xfe, 0x6b, 0xab, 0x62,
	0x9a, 0x92, 0xb9, 0x7c, 0x4c, 0x1a, 0x8a, 0xc0, 0xee, 0xaa, 0x4c, 0x51, 0xb7, 0x24, 0xf5, 0xf6,
	0x8a, 0x56, 0x62, 0x03, 0x60, 0x9e, 0x14, 0x94, 0x5a, 0xed, 0x52, 0x10, 0xa0, 0xb2, 0x7b, 0xbf,
	0x67, 0xfd, 0x47, 0x71, 0x22, 0x4e, 0xc7, 0x47, 0x88, 0xb0, 0xd4, 0x23, 0x8c, 0xa7, 0x8c, 0xeb,
	0xcf, 0x3e, 0x3f, 0x3e, 0xf3, 0xe4, 0xeb, 0x42, 0xaf, 0x29, 0x09, 0xa5, 0x37, 0x78, 0x77, 0x3e,
	0xb7, 0x8d, 0x8b, 0xb9, 0x6d, 0xfc, 0x99, 0xdb, 0xc6, 0x8f, 0x85, 0xdd, 0xb8, 0x58, 0xd8, 0x8d,
	0x5f, 0x0b, 0xbb, 0xf1, 0xc9, 0xaf, 0x72, 0x2a, 0xd7, 0x59, 0x99, 0xdc, 0xaf, 0xd5, 0x51, 0x94,
	0xe4, 0xa3, 0xb6, 0x9c, 0xc0, 0xa7, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xb8, 0x23, 0xf2, 0x39,
	0x5f, 0x04, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.VestingAccountTraceCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.VestingAccountTraceCount))
		i--
		dAtA[i] = 0x28
	}
	if len(m.VestingAccountTraces) > 0 {
		for iNdEx := len(m.VestingAccountTraces) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.VestingAccountTraces[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.AccountVestingPools) > 0 {
		for iNdEx := len(m.AccountVestingPools) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.AccountVestingPools[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.VestingTypes) > 0 {
		for iNdEx := len(m.VestingTypes) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.VestingTypes[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *GenesisVestingType) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisVestingType) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisVestingType) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Free.Size()
		i -= size
		if _, err := m.Free.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	if len(m.VestingPeriodUnit) > 0 {
		i -= len(m.VestingPeriodUnit)
		copy(dAtA[i:], m.VestingPeriodUnit)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.VestingPeriodUnit)))
		i--
		dAtA[i] = 0x2a
	}
	if m.VestingPeriod != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.VestingPeriod))
		i--
		dAtA[i] = 0x20
	}
	if len(m.LockupPeriodUnit) > 0 {
		i -= len(m.LockupPeriodUnit)
		copy(dAtA[i:], m.LockupPeriodUnit)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.LockupPeriodUnit)))
		i--
		dAtA[i] = 0x1a
	}
	if m.LockupPeriod != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.LockupPeriod))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.VestingTypes) > 0 {
		for _, e := range m.VestingTypes {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.AccountVestingPools) > 0 {
		for _, e := range m.AccountVestingPools {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.VestingAccountTraces) > 0 {
		for _, e := range m.VestingAccountTraces {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.VestingAccountTraceCount != 0 {
		n += 1 + sovGenesis(uint64(m.VestingAccountTraceCount))
	}
	return n
}

func (m *GenesisVestingType) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.LockupPeriod != 0 {
		n += 1 + sovGenesis(uint64(m.LockupPeriod))
	}
	l = len(m.LockupPeriodUnit)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.VestingPeriod != 0 {
		n += 1 + sovGenesis(uint64(m.VestingPeriod))
	}
	l = len(m.VestingPeriodUnit)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = m.Free.Size()
	n += 1 + l + sovGenesis(uint64(l))
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VestingTypes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VestingTypes = append(m.VestingTypes, GenesisVestingType{})
			if err := m.VestingTypes[len(m.VestingTypes)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccountVestingPools", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AccountVestingPools = append(m.AccountVestingPools, &AccountVestingPools{})
			if err := m.AccountVestingPools[len(m.AccountVestingPools)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VestingAccountTraces", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VestingAccountTraces = append(m.VestingAccountTraces, VestingAccountTrace{})
			if err := m.VestingAccountTraces[len(m.VestingAccountTraces)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VestingAccountTraceCount", wireType)
			}
			m.VestingAccountTraceCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VestingAccountTraceCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GenesisVestingType) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisVestingType: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisVestingType: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LockupPeriod", wireType)
			}
			m.LockupPeriod = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LockupPeriod |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LockupPeriodUnit", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LockupPeriodUnit = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VestingPeriod", wireType)
			}
			m.VestingPeriod = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VestingPeriod |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VestingPeriodUnit", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VestingPeriodUnit = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Free", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Free.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
