// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cfevesting/query.proto

package types

import (
	context "context"
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a48d110cdc5bffa, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a48d110cdc5bffa, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryVestingTypeRequest struct {
}

func (m *QueryVestingTypeRequest) Reset()         { *m = QueryVestingTypeRequest{} }
func (m *QueryVestingTypeRequest) String() string { return proto.CompactTextString(m) }
func (*QueryVestingTypeRequest) ProtoMessage()    {}
func (*QueryVestingTypeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a48d110cdc5bffa, []int{2}
}
func (m *QueryVestingTypeRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryVestingTypeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryVestingTypeRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryVestingTypeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryVestingTypeRequest.Merge(m, src)
}
func (m *QueryVestingTypeRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryVestingTypeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryVestingTypeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryVestingTypeRequest proto.InternalMessageInfo

type QueryVestingTypeResponse struct {
	VestingTypes VestingTypes `protobuf:"bytes,1,opt,name=vesting_types,json=vestingTypes,proto3" json:"vesting_types" yaml:"vesting_types"`
}

func (m *QueryVestingTypeResponse) Reset()         { *m = QueryVestingTypeResponse{} }
func (m *QueryVestingTypeResponse) String() string { return proto.CompactTextString(m) }
func (*QueryVestingTypeResponse) ProtoMessage()    {}
func (*QueryVestingTypeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a48d110cdc5bffa, []int{3}
}
func (m *QueryVestingTypeResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryVestingTypeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryVestingTypeResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryVestingTypeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryVestingTypeResponse.Merge(m, src)
}
func (m *QueryVestingTypeResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryVestingTypeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryVestingTypeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryVestingTypeResponse proto.InternalMessageInfo

func (m *QueryVestingTypeResponse) GetVestingTypes() VestingTypes {
	if m != nil {
		return m.VestingTypes
	}
	return VestingTypes{}
}

type QueryVestingRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *QueryVestingRequest) Reset()         { *m = QueryVestingRequest{} }
func (m *QueryVestingRequest) String() string { return proto.CompactTextString(m) }
func (*QueryVestingRequest) ProtoMessage()    {}
func (*QueryVestingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a48d110cdc5bffa, []int{4}
}
func (m *QueryVestingRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryVestingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryVestingRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryVestingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryVestingRequest.Merge(m, src)
}
func (m *QueryVestingRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryVestingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryVestingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryVestingRequest proto.InternalMessageInfo

func (m *QueryVestingRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type QueryVestingResponse struct {
	DelegableAddress string         `protobuf:"bytes,1,opt,name=delegable_address,json=delegableAddress,proto3" json:"delegable_address,omitempty" yaml:"delegable_address"`
	Vestings         []*VestingInfo `protobuf:"bytes,2,rep,name=vestings,proto3" json:"vestings,omitempty"`
}

func (m *QueryVestingResponse) Reset()         { *m = QueryVestingResponse{} }
func (m *QueryVestingResponse) String() string { return proto.CompactTextString(m) }
func (*QueryVestingResponse) ProtoMessage()    {}
func (*QueryVestingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a48d110cdc5bffa, []int{5}
}
func (m *QueryVestingResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryVestingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryVestingResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryVestingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryVestingResponse.Merge(m, src)
}
func (m *QueryVestingResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryVestingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryVestingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryVestingResponse proto.InternalMessageInfo

func (m *QueryVestingResponse) GetDelegableAddress() string {
	if m != nil {
		return m.DelegableAddress
	}
	return ""
}

func (m *QueryVestingResponse) GetVestings() []*VestingInfo {
	if m != nil {
		return m.Vestings
	}
	return nil
}

type VestingInfo struct {
	Id                  int32       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	VestingType         string      `protobuf:"bytes,2,opt,name=vesting_type,json=vestingType,proto3" json:"vesting_type,omitempty"`
	VestingStart        int64       `protobuf:"varint,3,opt,name=vesting_start,json=vestingStart,proto3" json:"vesting_start,omitempty"`
	LockEnd             int64       `protobuf:"varint,4,opt,name=lock_end,json=lockEnd,proto3" json:"lock_end,omitempty"`
	VestingEnd          int64       `protobuf:"varint,5,opt,name=vesting_end,json=vestingEnd,proto3" json:"vesting_end,omitempty"`
	Withdrawable        string      `protobuf:"bytes,6,opt,name=withdrawable,proto3" json:"withdrawable,omitempty"`
	DelegationAllowed   bool        `protobuf:"varint,7,opt,name=delegation_allowed,json=delegationAllowed,proto3" json:"delegation_allowed,omitempty"`
	Vested              *types.Coin `protobuf:"bytes,8,opt,name=vested,proto3" json:"vested,omitempty"`
	CurrentVestedAmount string      `protobuf:"bytes,9,opt,name=current_vested_amount,json=currentVestedAmount,proto3" json:"current_vested_amount,omitempty"`
	SentAmount          string      `protobuf:"bytes,10,opt,name=sent_amount,json=sentAmount,proto3" json:"sent_amount,omitempty"`
}

func (m *VestingInfo) Reset()         { *m = VestingInfo{} }
func (m *VestingInfo) String() string { return proto.CompactTextString(m) }
func (*VestingInfo) ProtoMessage()    {}
func (*VestingInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a48d110cdc5bffa, []int{6}
}
func (m *VestingInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VestingInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VestingInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *VestingInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VestingInfo.Merge(m, src)
}
func (m *VestingInfo) XXX_Size() int {
	return m.Size()
}
func (m *VestingInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_VestingInfo.DiscardUnknown(m)
}

var xxx_messageInfo_VestingInfo proto.InternalMessageInfo

func (m *VestingInfo) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *VestingInfo) GetVestingType() string {
	if m != nil {
		return m.VestingType
	}
	return ""
}

func (m *VestingInfo) GetVestingStart() int64 {
	if m != nil {
		return m.VestingStart
	}
	return 0
}

func (m *VestingInfo) GetLockEnd() int64 {
	if m != nil {
		return m.LockEnd
	}
	return 0
}

func (m *VestingInfo) GetVestingEnd() int64 {
	if m != nil {
		return m.VestingEnd
	}
	return 0
}

func (m *VestingInfo) GetWithdrawable() string {
	if m != nil {
		return m.Withdrawable
	}
	return ""
}

func (m *VestingInfo) GetDelegationAllowed() bool {
	if m != nil {
		return m.DelegationAllowed
	}
	return false
}

func (m *VestingInfo) GetVested() *types.Coin {
	if m != nil {
		return m.Vested
	}
	return nil
}

func (m *VestingInfo) GetCurrentVestedAmount() string {
	if m != nil {
		return m.CurrentVestedAmount
	}
	return ""
}

func (m *VestingInfo) GetSentAmount() string {
	if m != nil {
		return m.SentAmount
	}
	return ""
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "chain4energy.c4echain.cfevesting.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "chain4energy.c4echain.cfevesting.QueryParamsResponse")
	proto.RegisterType((*QueryVestingTypeRequest)(nil), "chain4energy.c4echain.cfevesting.QueryVestingTypeRequest")
	proto.RegisterType((*QueryVestingTypeResponse)(nil), "chain4energy.c4echain.cfevesting.QueryVestingTypeResponse")
	proto.RegisterType((*QueryVestingRequest)(nil), "chain4energy.c4echain.cfevesting.QueryVestingRequest")
	proto.RegisterType((*QueryVestingResponse)(nil), "chain4energy.c4echain.cfevesting.QueryVestingResponse")
	proto.RegisterType((*VestingInfo)(nil), "chain4energy.c4echain.cfevesting.VestingInfo")
}

func init() { proto.RegisterFile("cfevesting/query.proto", fileDescriptor_1a48d110cdc5bffa) }

var fileDescriptor_1a48d110cdc5bffa = []byte{
	// 736 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0xcf, 0x6b, 0x13, 0x41,
	0x14, 0xce, 0xa6, 0x6d, 0x92, 0x4e, 0xaa, 0xd8, 0x69, 0xb4, 0xdb, 0x10, 0x36, 0x71, 0x2d, 0x18,
	0x0b, 0xdd, 0xa1, 0x31, 0x15, 0xec, 0xad, 0x11, 0x85, 0x5e, 0x44, 0x57, 0xe9, 0x41, 0x90, 0x30,
	0xd9, 0x9d, 0x6e, 0x17, 0x93, 0x99, 0xed, 0xee, 0xa6, 0x35, 0x88, 0x17, 0xf1, 0x2a, 0x08, 0x1e,
	0xfd, 0x0b, 0x04, 0x0f, 0xfe, 0x19, 0x3d, 0x16, 0xbc, 0x78, 0x2a, 0xd2, 0xfa, 0x17, 0xf4, 0xec,
	0x41, 0xe6, 0x47, 0x92, 0x5d, 0x22, 0xb6, 0xf5, 0x94, 0xcc, 0xfb, 0xbe, 0xf7, 0xbd, 0x6f, 0xde,
	0xcc, 0x9b, 0x05, 0x37, 0x9c, 0x1d, 0xb2, 0x4f, 0xa2, 0xd8, 0xa7, 0x1e, 0xda, 0xeb, 0x93, 0x70,
	0x60, 0x05, 0x21, 0x8b, 0x19, 0xac, 0x39, 0xbb, 0xd8, 0xa7, 0x4d, 0x42, 0x49, 0xe8, 0x0d, 0x2c,
	0xa7, 0x49, 0xc4, 0xda, 0x1a, 0xb3, 0xcb, 0x25, 0x8f, 0x79, 0x4c, 0x90, 0x11, 0xff, 0x27, 0xf3,
	0xca, 0x15, 0x8f, 0x31, 0xaf, 0x4b, 0x10, 0x0e, 0x7c, 0x84, 0x29, 0x65, 0x31, 0x8e, 0x7d, 0x46,
	0x23, 0x85, 0xae, 0x38, 0x2c, 0xea, 0xb1, 0x08, 0x75, 0x70, 0x44, 0x64, 0x39, 0xb4, 0xbf, 0xd6,
	0x21, 0x31, 0x5e, 0x43, 0x01, 0xf6, 0x7c, 0x2a, 0xc8, 0x8a, 0xbb, 0x98, 0x70, 0x16, 0xe0, 0x10,
	0xf7, 0x86, 0x22, 0x46, 0x02, 0x50, 0xbf, 0xed, 0x78, 0x10, 0x90, 0x31, 0x9e, 0x28, 0x32, 0x94,
	0x77, 0x98, 0xaf, 0x84, 0xcd, 0x12, 0x80, 0x4f, 0x79, 0xe9, 0x27, 0x42, 0xd4, 0x26, 0x7b, 0x7d,
	0x12, 0xc5, 0xe6, 0x4b, 0xb0, 0x90, 0x8a, 0x46, 0x01, 0xa3, 0x11, 0x81, 0x8f, 0x40, 0x4e, 0x16,
	0xd7, 0xb5, 0x9a, 0x56, 0x2f, 0x36, 0xea, 0xd6, 0x79, 0x8d, 0xb1, 0xa4, 0x42, 0x6b, 0xfa, 0xf0,
	0xb8, 0x9a, 0xb1, 0x55, 0xb6, 0xb9, 0x04, 0x16, 0x85, 0xfc, 0xb6, 0x24, 0x3d, 0x1f, 0x04, 0x64,
	0x58, 0xf9, 0x83, 0x06, 0xf4, 0x49, 0x4c, 0xd5, 0xdf, 0x03, 0x57, 0x52, 0x7b, 0x54, 0x36, 0xac,
	0xf3, 0x6d, 0x24, 0xd4, 0xa2, 0x56, 0x85, 0x9b, 0x39, 0x3b, 0xae, 0x96, 0x06, 0xb8, 0xd7, 0xdd,
	0x30, 0x53, 0x92, 0xa6, 0x3d, 0xb7, 0x9f, 0xe0, 0x9a, 0x48, 0x75, 0x42, 0x09, 0x28, 0x9b, 0x50,
	0x07, 0x79, 0xec, 0xba, 0x21, 0x89, 0xa4, 0x87, 0x59, 0x7b, 0xb8, 0x34, 0xbf, 0x6a, 0xa0, 0x94,
	0xce, 0x50, 0xe6, 0xb7, 0xc0, 0xbc, 0x4b, 0xba, 0xc4, 0xc3, 0x9d, 0x2e, 0x69, 0xa7, 0x92, 0x5b,
	0x95, 0xb3, 0xe3, 0xaa, 0x2e, 0xcd, 0x4c, 0x50, 0x4c, 0xfb, 0xda, 0x28, 0xb6, 0x29, 0x43, 0x70,
	0x0b, 0x14, 0x94, 0xc9, 0x48, 0xcf, 0xd6, 0xa6, 0xea, 0xc5, 0xc6, 0xea, 0x85, 0x5b, 0xb0, 0x45,
	0x77, 0x98, 0x3d, 0x4a, 0x37, 0x7f, 0x67, 0x41, 0x31, 0x81, 0xc0, 0xab, 0x20, 0xeb, 0xbb, 0xc2,
	0xd6, 0x8c, 0x9d, 0xf5, 0x5d, 0x78, 0x13, 0xcc, 0x25, 0xfb, 0xa3, 0x67, 0xc5, 0x6e, 0x8b, 0x89,
	0x1e, 0xc1, 0x5b, 0xe3, 0x53, 0x89, 0x62, 0x1c, 0xc6, 0xfa, 0x54, 0x4d, 0xab, 0x4f, 0x8d, 0xfa,
	0xf8, 0x8c, 0xc7, 0xe0, 0x12, 0x28, 0x74, 0x99, 0xf3, 0xaa, 0x4d, 0xa8, 0xab, 0x4f, 0x0b, 0x3c,
	0xcf, 0xd7, 0x0f, 0xa9, 0x0b, 0xab, 0x60, 0x28, 0x27, 0xd0, 0x19, 0x81, 0x02, 0x15, 0xe2, 0x04,
	0x13, 0xcc, 0x1d, 0xf8, 0xf1, 0xae, 0x1b, 0xe2, 0x03, 0xde, 0x05, 0x3d, 0x27, 0x3c, 0xa4, 0x62,
	0x70, 0x15, 0x40, 0xd9, 0x26, 0x3e, 0x34, 0x6d, 0xdc, 0xed, 0xb2, 0x03, 0xe2, 0xea, 0xf9, 0x9a,
	0x56, 0x2f, 0xd8, 0xf3, 0x63, 0x64, 0x53, 0x02, 0x70, 0x0d, 0xe4, 0x78, 0x01, 0xe2, 0xea, 0x05,
	0x71, 0x85, 0x96, 0x2c, 0x39, 0x27, 0x16, 0x9f, 0x13, 0x4b, 0xcd, 0x89, 0xf5, 0x80, 0xf9, 0xd4,
	0x56, 0x44, 0xd8, 0x00, 0xd7, 0x9d, 0x7e, 0x18, 0x12, 0x1a, 0xb7, 0x65, 0xa4, 0x8d, 0x7b, 0xac,
	0x4f, 0x63, 0x7d, 0x56, 0xd8, 0x59, 0x50, 0xe0, 0xb6, 0xc0, 0x36, 0x05, 0xc4, 0xb7, 0x16, 0xf1,
	0x04, 0xc5, 0x04, 0x82, 0x09, 0x78, 0x48, 0x12, 0x1a, 0xef, 0xa7, 0xc1, 0x8c, 0xb8, 0x2d, 0xf0,
	0xb3, 0x06, 0x72, 0x72, 0x58, 0x60, 0xf3, 0xfc, 0xc3, 0x9c, 0x9c, 0xd9, 0xf2, 0xfa, 0x25, 0xb3,
	0xe4, 0xb5, 0x34, 0x97, 0xdf, 0x7d, 0xff, 0xf5, 0x29, 0x6b, 0xc0, 0x0a, 0x4a, 0xa6, 0xa3, 0xf4,
	0x63, 0x03, 0xbf, 0x69, 0xa3, 0x6b, 0x22, 0xce, 0xfc, 0xfe, 0x05, 0x8b, 0x4d, 0x4e, 0x78, 0x79,
	0xe3, 0x7f, 0x52, 0x95, 0xd9, 0x15, 0x61, 0x76, 0x19, 0x9a, 0x7f, 0x37, 0x9b, 0xbc, 0xa9, 0xf0,
	0x8b, 0x06, 0xf2, 0x4a, 0x03, 0xae, 0x5f, 0xae, 0xe6, 0xd0, 0xea, 0xbd, 0xcb, 0xa6, 0x29, 0x9b,
	0x48, 0xd8, 0xbc, 0x03, 0x6f, 0xff, 0xd3, 0x26, 0x7a, 0xa3, 0x46, 0xfc, 0x6d, 0xeb, 0xf1, 0xe1,
	0x89, 0xa1, 0x1d, 0x9d, 0x18, 0xda, 0xcf, 0x13, 0x43, 0xfb, 0x78, 0x6a, 0x64, 0x8e, 0x4e, 0x8d,
	0xcc, 0x8f, 0x53, 0x23, 0xf3, 0xa2, 0xe9, 0xf9, 0xf1, 0x6e, 0xbf, 0x63, 0x39, 0xac, 0x97, 0x16,
	0x73, 0x9a, 0x64, 0x55, 0x04, 0xd0, 0x6b, 0x94, 0xf8, 0x06, 0x88, 0x47, 0xac, 0x93, 0x13, 0x8f,
	0xfb, 0xdd, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xed, 0xc5, 0xae, 0x28, 0xd1, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of VestingType items.
	VestingType(ctx context.Context, in *QueryVestingTypeRequest, opts ...grpc.CallOption) (*QueryVestingTypeResponse, error)
	// Queries a list of Vesting items.
	Vesting(ctx context.Context, in *QueryVestingRequest, opts ...grpc.CallOption) (*QueryVestingResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/chain4energy.c4echain.cfevesting.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) VestingType(ctx context.Context, in *QueryVestingTypeRequest, opts ...grpc.CallOption) (*QueryVestingTypeResponse, error) {
	out := new(QueryVestingTypeResponse)
	err := c.cc.Invoke(ctx, "/chain4energy.c4echain.cfevesting.Query/VestingType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Vesting(ctx context.Context, in *QueryVestingRequest, opts ...grpc.CallOption) (*QueryVestingResponse, error) {
	out := new(QueryVestingResponse)
	err := c.cc.Invoke(ctx, "/chain4energy.c4echain.cfevesting.Query/Vesting", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of VestingType items.
	VestingType(context.Context, *QueryVestingTypeRequest) (*QueryVestingTypeResponse, error)
	// Queries a list of Vesting items.
	Vesting(context.Context, *QueryVestingRequest) (*QueryVestingResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) VestingType(ctx context.Context, req *QueryVestingTypeRequest) (*QueryVestingTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VestingType not implemented")
}
func (*UnimplementedQueryServer) Vesting(ctx context.Context, req *QueryVestingRequest) (*QueryVestingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Vesting not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chain4energy.c4echain.cfevesting.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_VestingType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryVestingTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).VestingType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chain4energy.c4echain.cfevesting.Query/VestingType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).VestingType(ctx, req.(*QueryVestingTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Vesting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryVestingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Vesting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chain4energy.c4echain.cfevesting.Query/Vesting",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Vesting(ctx, req.(*QueryVestingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "chain4energy.c4echain.cfevesting.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "VestingType",
			Handler:    _Query_VestingType_Handler,
		},
		{
			MethodName: "Vesting",
			Handler:    _Query_Vesting_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cfevesting/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryVestingTypeRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryVestingTypeRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryVestingTypeRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryVestingTypeResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryVestingTypeResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryVestingTypeResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.VestingTypes.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryVestingRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryVestingRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryVestingRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryVestingResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryVestingResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryVestingResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Vestings) > 0 {
		for iNdEx := len(m.Vestings) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Vestings[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.DelegableAddress) > 0 {
		i -= len(m.DelegableAddress)
		copy(dAtA[i:], m.DelegableAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.DelegableAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *VestingInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VestingInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VestingInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.SentAmount) > 0 {
		i -= len(m.SentAmount)
		copy(dAtA[i:], m.SentAmount)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.SentAmount)))
		i--
		dAtA[i] = 0x52
	}
	if len(m.CurrentVestedAmount) > 0 {
		i -= len(m.CurrentVestedAmount)
		copy(dAtA[i:], m.CurrentVestedAmount)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.CurrentVestedAmount)))
		i--
		dAtA[i] = 0x4a
	}
	if m.Vested != nil {
		{
			size, err := m.Vested.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x42
	}
	if m.DelegationAllowed {
		i--
		if m.DelegationAllowed {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x38
	}
	if len(m.Withdrawable) > 0 {
		i -= len(m.Withdrawable)
		copy(dAtA[i:], m.Withdrawable)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Withdrawable)))
		i--
		dAtA[i] = 0x32
	}
	if m.VestingEnd != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.VestingEnd))
		i--
		dAtA[i] = 0x28
	}
	if m.LockEnd != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.LockEnd))
		i--
		dAtA[i] = 0x20
	}
	if m.VestingStart != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.VestingStart))
		i--
		dAtA[i] = 0x18
	}
	if len(m.VestingType) > 0 {
		i -= len(m.VestingType)
		copy(dAtA[i:], m.VestingType)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.VestingType)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryVestingTypeRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryVestingTypeResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.VestingTypes.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryVestingRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryVestingResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.DelegableAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if len(m.Vestings) > 0 {
		for _, e := range m.Vestings {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *VestingInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	l = len(m.VestingType)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.VestingStart != 0 {
		n += 1 + sovQuery(uint64(m.VestingStart))
	}
	if m.LockEnd != 0 {
		n += 1 + sovQuery(uint64(m.LockEnd))
	}
	if m.VestingEnd != 0 {
		n += 1 + sovQuery(uint64(m.VestingEnd))
	}
	l = len(m.Withdrawable)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.DelegationAllowed {
		n += 2
	}
	if m.Vested != nil {
		l = m.Vested.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.CurrentVestedAmount)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.SentAmount)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryVestingTypeRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryVestingTypeRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryVestingTypeRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryVestingTypeResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryVestingTypeResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryVestingTypeResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VestingTypes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.VestingTypes.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryVestingRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryVestingRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryVestingRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryVestingResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryVestingResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryVestingResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DelegableAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DelegableAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Vestings", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Vestings = append(m.Vestings, &VestingInfo{})
			if err := m.Vestings[len(m.Vestings)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VestingInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VestingInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VestingInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VestingType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VestingType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VestingStart", wireType)
			}
			m.VestingStart = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VestingStart |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LockEnd", wireType)
			}
			m.LockEnd = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LockEnd |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VestingEnd", wireType)
			}
			m.VestingEnd = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VestingEnd |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Withdrawable", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Withdrawable = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DelegationAllowed", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.DelegationAllowed = bool(v != 0)
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Vested", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Vested == nil {
				m.Vested = &types.Coin{}
			}
			if err := m.Vested.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentVestedAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CurrentVestedAmount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SentAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SentAmount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
